// Express entry point; serves public/ static files, mounts /api/* routers, catch-all returns index.html for SPA deep links.

// Code generated by Sonnet 4.6
import express from 'express';
const app = express();
app.use(express.json());

import { readdirSync } from 'fs';
import { pathToFileURL } from 'url';
import path from 'path';

const routesDir = './routes';
for (const strFile of readdirSync(routesDir)) {
    if (!strFile.endsWith('.js')) continue;
    const strName = strFile.replace('.js', '');
    const { default: router } = await import(pathToFileURL(path.resolve(routesDir, strFile)).href);
    app.use(`/api/${strName}`, router);
}

app.listen(3030);