// Express entry point; serves public/ static files, mounts /api/* routers, catch-all returns index.html for SPA deep links.

// Code generated by Sonnet 4.6
import "dotenv/config";
import express from "express";
import { readdirSync } from "fs";
import { pathToFileURL, fileURLToPath } from "url";
import path from "path";

// __dirname equivalent for ES modules
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const app = express();
app.use(express.json());

// Dynamically load all route modules from /routes/ and mount each under /api/<name>
const routesDir = path.join(__dirname, "routes");
for (const strFile of readdirSync(routesDir)) {
    if (!strFile.endsWith(".js")) continue;
    const strName = strFile.replace(".js", "");
    const { default: router } = await import(
        pathToFileURL(path.resolve(routesDir, strFile)).href
    );
    app.use(`/api/${strName}`, router);
}

// Serve static files (HTML, CSS, JS, vendor assets) from public/
app.use(express.static(path.join(__dirname, "public")));

// SPA catch-all: return index.html for any non-/api path so deep links and refreshes resolve correctly
app.get("*", (req, res, next) => {
    if (req.path.startsWith("/api/")) return next();
    res.sendFile(path.join(__dirname, "public", "index.html"));
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`Server running on http://localhost:${PORT}`);
});
