// RESTful router for GET /api/contact and PUT /api/contact (single-row contact record).
import db from '../lib/db.js';
import { Router } from 'express';

const router = Router();

router.get("/", (req, res) => {
    let arrContact = db.prepare("SELECT * FROM contact").all();
    arrContact[0].links_json = JSON.parse(arrContact[0].links_json);
    res.status(200).json(arrContact);
});

router.put("/", (req, res) => {
    const full_name = req.body.full_name ?? "";
    const email = req.body.email ?? "";
    const phone = req.body.phone ?? "";
    const location = req.body.location ?? "";
    let links_json = req.body.links_json ?? [];
    //updated_at handled by SQL Trigger

    // Validation code generated by Sonnet 4.6
    const blnValid = links_json.every(item =>
        item !== null &&
        typeof item === "object" &&
        typeof item.label === "string" && item.label.trim() !== "" &&
        typeof item.url === "string" && item.url.trim() !== ""
    );
    if (!blnValid) {
        return res.status(400).json({ message: "Each link must have a non-empty label and url" });
    }
    links_json = JSON.stringify(links_json);

    const strQuery = "UPDATE contact SET full_name = @full_name, email = @email, phone = @phone, location = @location, links_json = @links_json WHERE id = 1";
    db.prepare(strQuery).run({ full_name, email, phone, location, links_json });
    res.status(200).json({ message: "Contact information updated successfully" });
});

export default router;
