// RESTful router for contact info (single-row record — always id = 1, seeded by schema.sql).
//
// Routes:
//   GET /api/contact — retrieve contact record; links_json is parsed from stored JSON string to an array
//   PUT /api/contact — update contact record; links_json array is validated then serialized back to JSON string
import db from "../lib/db.js";
import { Router } from "express";

const router = Router();

router.get("/", (req, res) => {
    try {
        const arrContact = db.prepare("SELECT * FROM contact").all();
        // links_json is stored as a JSON text string in SQLite; parse it back to an array before responding
        arrContact[0].links_json = JSON.parse(arrContact[0].links_json);
        res.status(200).json(arrContact);
    } catch (err) {
        console.error("GET /api/contact error:", err);
        res.status(500).json({
            message: "Failed to retrieve contact information",
        });
    }
});

router.put("/", (req, res) => {
    const full_name = (req.body.full_name ?? "").trim();
    const email = (req.body.email ?? "").trim();
    const phone = (req.body.phone ?? "").trim();
    const location = (req.body.location ?? "").trim();
    let links_json = req.body.links_json ?? [];
    // updated_at handled by SQL trigger — no need to set it manually

    // Validation code generated by Sonnet 4.6
    if (!Array.isArray(links_json)) {
        return res.status(400).json({ message: "links_json must be an array" });
    }
    const blnValid = links_json.every(
        (item) =>
            item !== null &&
            typeof item === "object" &&
            typeof item.label === "string" &&
            item.label.trim() !== "" &&
            typeof item.url === "string" &&
            item.url.trim() !== "",
    );
    if (!blnValid) {
        return res
            .status(400)
            .json({ message: "Each link must have a non-empty label and url" });
    }
    links_json = JSON.stringify(links_json);

    const strQuery =
        "UPDATE contact SET full_name = @full_name, email = @email, phone = @phone, location = @location, links_json = @links_json WHERE id = 1";
    db.prepare(strQuery).run({ full_name, email, phone, location, links_json });
    res.status(200).json({
        message: "Contact information updated successfully",
    });
});

export default router;
