// OpenAPI 3.0 spec for the Resume Frog API.
// All routes and schemas defined here — edit this file to update the Swagger UI at /api/swagger.
// Generated by Sonnet 4.6

const swaggerSpec = {
    openapi: "3.0.0",
    info: {
        title: "Resume Frog API",
        version: "1.0.0",
        description: "REST API for the Resume Frog local SPA (CSC3100).",
    },
    servers: [{ url: "/api", description: "API base" }],

    // ─────────────────────────────────────────────
    // Reusable schemas
    // ─────────────────────────────────────────────
    components: {
        schemas: {
            // ── Shared ──────────────────────────
            MessageResponse: {
                type: "object",
                properties: {
                    message: { type: "string" },
                },
            },
            CreatedResponse: {
                type: "object",
                properties: {
                    message: { type: "string" },
                    id: { type: "integer" },
                },
            },
            ErrorResponse: {
                type: "object",
                properties: {
                    message: { type: "string" },
                },
            },
            Link: {
                type: "object",
                required: ["label", "url"],
                properties: {
                    label: { type: "string", example: "GitHub" },
                    url: { type: "string", example: "https://github.com/username" },
                },
            },

            // ── Contact ─────────────────────────
            Contact: {
                type: "object",
                properties: {
                    id: { type: "integer", example: 1 },
                    full_name: { type: "string", example: "Jane Doe" },
                    email: { type: "string", example: "jane@example.com" },
                    phone: { type: "string", example: "555-1234" },
                    location: { type: "string", example: "Austin, TX" },
                    links_json: {
                        type: "array",
                        items: { $ref: "#/components/schemas/Link" },
                    },
                    updated_at: { type: "string", example: "2024-01-01 12:00:00" },
                },
            },
            ContactInput: {
                type: "object",
                properties: {
                    full_name: { type: "string" },
                    email: { type: "string" },
                    phone: { type: "string" },
                    location: { type: "string" },
                    links_json: {
                        type: "array",
                        items: { $ref: "#/components/schemas/Link" },
                    },
                },
            },

            // ── Summary ─────────────────────────
            Summary: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    label: { type: "string", example: "Software Engineer" },
                    content: { type: "string", example: "Experienced full-stack developer..." },
                    sort_order: { type: "integer" },
                    updated_at: { type: "string" },
                },
            },
            SummaryInput: {
                type: "object",
                properties: {
                    label: { type: "string" },
                    content: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Education ───────────────────────
            Education: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    institution: { type: "string", example: "State University" },
                    degree: { type: "string", example: "B.S." },
                    field: { type: "string", example: "Computer Science" },
                    start_date: { type: "string", example: "2020-08" },
                    end_date: { type: "string", example: "2024-05" },
                    gpa: { type: "string", example: "3.8" },
                    details: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },
            EducationInput: {
                type: "object",
                required: ["institution"],
                properties: {
                    institution: { type: "string" },
                    degree: { type: "string" },
                    field: { type: "string" },
                    start_date: { type: "string" },
                    end_date: { type: "string" },
                    gpa: { type: "string" },
                    details: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Jobs ────────────────────────────
            Job: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    company: { type: "string", example: "Acme Corp" },
                    title: { type: "string", example: "Software Engineer" },
                    location: { type: "string", example: "Remote" },
                    start_date: { type: "string", example: "2022-06" },
                    end_date: { type: "string", example: "2024-01" },
                    is_current: { type: "integer", enum: [0, 1] },
                    sort_order: { type: "integer" },
                },
            },
            JobInput: {
                type: "object",
                required: ["company"],
                properties: {
                    company: { type: "string" },
                    title: { type: "string" },
                    location: { type: "string" },
                    start_date: { type: "string" },
                    end_date: { type: "string" },
                    is_current: { type: "integer", enum: [0, 1] },
                    sort_order: { type: "integer" },
                },
            },
            Bullet: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    text: { type: "string", example: "Reduced API latency by 40%." },
                    sort_order: { type: "integer" },
                },
            },
            BulletInput: {
                type: "object",
                required: ["text"],
                properties: {
                    text: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Projects ────────────────────────
            Project: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    name: { type: "string", example: "Resume Frog" },
                    link: { type: "string", example: "https://github.com/user/project" },
                    description: { type: "string" },
                    start_date: { type: "string" },
                    end_date: { type: "string" },
                    is_current: { type: "integer", enum: [0, 1] },
                    sort_order: { type: "integer" },
                },
            },
            ProjectInput: {
                type: "object",
                required: ["name"],
                properties: {
                    name: { type: "string" },
                    link: { type: "string" },
                    description: { type: "string" },
                    start_date: { type: "string" },
                    end_date: { type: "string" },
                    is_current: { type: "integer", enum: [0, 1] },
                    sort_order: { type: "integer" },
                },
            },

            // ── Skill Categories ────────────────
            SkillCategory: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    name: { type: "string", example: "Languages" },
                    sort_order: { type: "integer" },
                },
            },
            SkillCategoryInput: {
                type: "object",
                required: ["name"],
                properties: {
                    name: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Skills ──────────────────────────
            Skill: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    category_id: { type: "integer", nullable: true },
                    name: { type: "string", example: "JavaScript" },
                    sort_order: { type: "integer" },
                },
            },
            SkillInput: {
                type: "object",
                required: ["name"],
                properties: {
                    category_id: { type: "integer", nullable: true },
                    name: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Certifications ──────────────────
            Certification: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    name: { type: "string", example: "AWS Solutions Architect" },
                    issuer: { type: "string", example: "Amazon" },
                    issued_date: { type: "string", example: "2023-05" },
                    sort_order: { type: "integer" },
                },
            },
            CertificationInput: {
                type: "object",
                required: ["name"],
                properties: {
                    name: { type: "string" },
                    issuer: { type: "string" },
                    issued_date: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Awards ──────────────────────────
            Award: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    name: { type: "string", example: "Dean's List" },
                    issuer: { type: "string", example: "State University" },
                    issued_date: { type: "string", example: "2023-05" },
                    description: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },
            AwardInput: {
                type: "object",
                required: ["name"],
                properties: {
                    name: { type: "string" },
                    issuer: { type: "string" },
                    issued_date: { type: "string" },
                    description: { type: "string" },
                    sort_order: { type: "integer" },
                },
            },

            // ── Resumes ─────────────────────────
            Resume: {
                type: "object",
                properties: {
                    id: { type: "integer" },
                    name: { type: "string", example: "SWE Resume" },
                    target_role: { type: "string", example: "Software Engineer" },
                    created_at: { type: "string" },
                    updated_at: { type: "string" },
                },
            },
            ResumeInput: {
                type: "object",
                required: ["name"],
                properties: {
                    name: { type: "string" },
                    target_role: { type: "string" },
                },
            },
            // Body for PUT /resumes/:id/selections — bulk upsert of sections/items/bullets
            ResumeSelections: {
                type: "object",
                properties: {
                    sections: {
                        type: "array",
                        items: {
                            type: "object",
                            properties: {
                                section_type: { type: "string" },
                                included: { type: "integer", enum: [0, 1] },
                                sort_order: { type: "integer" },
                            },
                        },
                    },
                    items: {
                        type: "array",
                        items: {
                            type: "object",
                            properties: {
                                section_type: { type: "string" },
                                item_id: { type: "integer" },
                                sort_order: { type: "integer" },
                            },
                        },
                    },
                    bullets: {
                        type: "array",
                        items: {
                            type: "object",
                            properties: {
                                parent_item_id: { type: "integer" },
                                bullet_type: { type: "string", enum: ["job", "project"] },
                                bullet_id: { type: "integer" },
                                sort_order: { type: "integer" },
                            },
                        },
                    },
                },
            },

            // ── AI ──────────────────────────────
            AiReviewInput: {
                type: "object",
                required: ["sectionType", "text"],
                properties: {
                    sectionType: {
                        type: "string",
                        enum: ["contact", "summary", "education", "jobs", "projects", "skills", "certifications", "awards"],
                    },
                    text: { type: "string" },
                },
            },
            AiReviewResponse: {
                type: "object",
                properties: {
                    suggestions: {
                        type: "array",
                        items: { type: "string" },
                    },
                },
            },
        },

        // ── Reusable path parameters ──────────────
        parameters: {
            IdParam: {
                name: "id",
                in: "path",
                required: true,
                schema: { type: "integer" },
            },
            BidParam: {
                name: "bid",
                in: "path",
                required: true,
                description: "Bullet ID",
                schema: { type: "integer" },
            },
        },
    },

    // ─────────────────────────────────────────────
    // Paths
    // ─────────────────────────────────────────────
    paths: {

        // ── Contact ─────────────────────────────
        "/contact": {
            get: {
                tags: ["Contact"],
                summary: "Get contact info",
                responses: {
                    200: {
                        description: "Contact record (always one-element array)",
                        content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Contact" } } } },
                    },
                },
            },
            put: {
                tags: ["Contact"],
                summary: "Update contact info",
                requestBody: {
                    required: true,
                    content: { "application/json": { schema: { $ref: "#/components/schemas/ContactInput" } } },
                },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Summary ─────────────────────────────
        "/summary": {
            get: {
                tags: ["Summary"],
                summary: "List all summary variants",
                responses: {
                    200: { description: "Array of summaries", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Summary" } } } } },
                },
            },
            post: {
                tags: ["Summary"],
                summary: "Create summary variant",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SummaryInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/summary/{id}": {
            get: {
                tags: ["Summary"],
                summary: "Get summary by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Summary record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Summary" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Summary"],
                summary: "Update summary",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SummaryInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Summary"],
                summary: "Delete summary",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Educations ──────────────────────────
        "/educations": {
            get: {
                tags: ["Educations"],
                summary: "List all education entries",
                responses: {
                    200: { description: "Array of educations", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Education" } } } } },
                },
            },
            post: {
                tags: ["Educations"],
                summary: "Create education entry",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/EducationInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/educations/{id}": {
            get: {
                tags: ["Educations"],
                summary: "Get education by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Education record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Education" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Educations"],
                summary: "Update education entry",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/EducationInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Educations"],
                summary: "Delete education entry",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Jobs ────────────────────────────────
        "/jobs": {
            get: {
                tags: ["Jobs"],
                summary: "List all jobs",
                responses: {
                    200: { description: "Array of jobs", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Job" } } } } },
                },
            },
            post: {
                tags: ["Jobs"],
                summary: "Create job",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/JobInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/jobs/{id}": {
            get: {
                tags: ["Jobs"],
                summary: "Get job by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Job record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Job" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Jobs"],
                summary: "Update job",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/JobInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Jobs"],
                summary: "Delete job",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/jobs/{id}/bullets": {
            get: {
                tags: ["Jobs"],
                summary: "List bullets for a job",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Array of bullets", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Bullet" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            post: {
                tags: ["Jobs"],
                summary: "Add bullet to job",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/BulletInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Job not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/jobs/{id}/bullets/{bid}": {
            put: {
                tags: ["Jobs"],
                summary: "Update job bullet",
                parameters: [{ $ref: "#/components/parameters/IdParam" }, { $ref: "#/components/parameters/BidParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/BulletInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Jobs"],
                summary: "Delete job bullet",
                parameters: [{ $ref: "#/components/parameters/IdParam" }, { $ref: "#/components/parameters/BidParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Projects ────────────────────────────
        "/projects": {
            get: {
                tags: ["Projects"],
                summary: "List all projects",
                responses: {
                    200: { description: "Array of projects", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Project" } } } } },
                },
            },
            post: {
                tags: ["Projects"],
                summary: "Create project",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ProjectInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/projects/{id}": {
            get: {
                tags: ["Projects"],
                summary: "Get project by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Project record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Project" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Projects"],
                summary: "Update project",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ProjectInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Projects"],
                summary: "Delete project",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/projects/{id}/bullets": {
            get: {
                tags: ["Projects"],
                summary: "List bullets for a project",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Array of bullets", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Bullet" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            post: {
                tags: ["Projects"],
                summary: "Add bullet to project",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/BulletInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Project not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/projects/{id}/bullets/{bid}": {
            put: {
                tags: ["Projects"],
                summary: "Update project bullet",
                parameters: [{ $ref: "#/components/parameters/IdParam" }, { $ref: "#/components/parameters/BidParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/BulletInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Projects"],
                summary: "Delete project bullet",
                parameters: [{ $ref: "#/components/parameters/IdParam" }, { $ref: "#/components/parameters/BidParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Skill Categories ────────────────────
        "/skill-categories": {
            get: {
                tags: ["Skills"],
                summary: "List all skill categories",
                responses: {
                    200: { description: "Array of categories", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/SkillCategory" } } } } },
                },
            },
            post: {
                tags: ["Skills"],
                summary: "Create skill category",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SkillCategoryInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/skill-categories/{id}": {
            get: {
                tags: ["Skills"],
                summary: "Get skill category by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Category record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/SkillCategory" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Skills"],
                summary: "Update skill category",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SkillCategoryInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Skills"],
                summary: "Delete skill category",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Skills ──────────────────────────────
        "/skills": {
            get: {
                tags: ["Skills"],
                summary: "List all skills",
                responses: {
                    200: { description: "Array of skills", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Skill" } } } } },
                },
            },
            post: {
                tags: ["Skills"],
                summary: "Create skill",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SkillInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/skills/{id}": {
            get: {
                tags: ["Skills"],
                summary: "Get skill by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Skill record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Skill" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Skills"],
                summary: "Update skill",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/SkillInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Skills"],
                summary: "Delete skill",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Certifications ──────────────────────
        "/certifications": {
            get: {
                tags: ["Certifications"],
                summary: "List all certifications",
                responses: {
                    200: { description: "Array of certifications", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Certification" } } } } },
                },
            },
            post: {
                tags: ["Certifications"],
                summary: "Create certification",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CertificationInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/certifications/{id}": {
            get: {
                tags: ["Certifications"],
                summary: "Get certification by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Certification record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Certification" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Certifications"],
                summary: "Update certification",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CertificationInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Certifications"],
                summary: "Delete certification",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Awards ──────────────────────────────
        "/awards": {
            get: {
                tags: ["Awards"],
                summary: "List all awards",
                responses: {
                    200: { description: "Array of awards", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Award" } } } } },
                },
            },
            post: {
                tags: ["Awards"],
                summary: "Create award",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AwardInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/awards/{id}": {
            get: {
                tags: ["Awards"],
                summary: "Get award by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Award record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Award" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Awards"],
                summary: "Update award",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AwardInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Awards"],
                summary: "Delete award",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── Resumes ─────────────────────────────
        "/resumes": {
            get: {
                tags: ["Resumes"],
                summary: "List all resumes",
                responses: {
                    200: { description: "Array of resumes", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Resume" } } } } },
                },
            },
            post: {
                tags: ["Resumes"],
                summary: "Create resume",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ResumeInput" } } } },
                responses: {
                    201: { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/CreatedResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/resumes/{id}": {
            get: {
                tags: ["Resumes"],
                summary: "Get resume by ID",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Resume record", content: { "application/json": { schema: { type: "array", items: { $ref: "#/components/schemas/Resume" } } } } },
                    400: { description: "Missing id", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            put: {
                tags: ["Resumes"],
                summary: "Update resume metadata",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ResumeInput" } } } },
                responses: {
                    200: { description: "Updated", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
            delete: {
                tags: ["Resumes"],
                summary: "Delete resume",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                responses: {
                    200: { description: "Deleted", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    404: { description: "Not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
        "/resumes/{id}/selections": {
            put: {
                tags: ["Resumes"],
                summary: "Bulk upsert sections, items, and bullets for a resume",
                parameters: [{ $ref: "#/components/parameters/IdParam" }],
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ResumeSelections" } } } },
                responses: {
                    200: { description: "Selections saved", content: { "application/json": { schema: { $ref: "#/components/schemas/MessageResponse" } } } },
                    400: { description: "Validation error", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                    404: { description: "Resume not found", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },

        // ── AI ──────────────────────────────────
        "/ai/review": {
            post: {
                tags: ["AI"],
                summary: "Review section text with Gemini AI",
                requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AiReviewInput" } } } },
                responses: {
                    200: { description: "Suggestions array", content: { "application/json": { schema: { $ref: "#/components/schemas/AiReviewResponse" } } } },
                    400: { description: "Missing key or invalid input", content: { "application/json": { schema: { $ref: "#/components/schemas/ErrorResponse" } } } },
                },
            },
        },
    },
};

export default swaggerSpec;
